version: '3.4'
services:      
  java-telemetry:
    image: ${DOCKER_REGISTRY:-dls}/java-telemetry:${TAG:-latest}
    build:
      context: ../
      dockerfile: dls_JavaTelemetry/Dockerfile
      args:
        JAR_FILE: dls_JavaTelemetry-0.0.1-SNAPSHOT.jar
    environment:
      - opentracing_jaeger_http-sender_url=${Jaeger__Endpoint:-http://jaeger:14268/api/traces}
      - spring_datasource_url=${Database__ConnectionString:-jdbc:sqlserver://mssql:1433;databaseName=Weather;encrypt=false;integratedSecurity=false}
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
      - loki
      - mssql